version: "3.2"
services:

  server:
    container_name: server-cont
    build: ./server
    image: server-img
    # restart: always
    # environment:
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - POSTGRES_PORT=5432

    # ports:
    #   - 50001:50000

  client:
    container_name: client-cont
    build: ./client
    image: client-img
    # restart: always
    # environment:
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - POSTGRES_PORT=5432

    # ports:
    #   - 50000:50000
    depends_on:
      - server

